-- Users table
CREATE TABLE USERS (
    ID VARCHAR(255) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    GENDER VARCHAR(20),
    ADDRESS VARCHAR(255),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Department table
CREATE TABLE DEPARTMENT (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Course table
CREATE TABLE COURSE (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DEPARTMENT_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Event table
CREATE TABLE EVENT (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    START_DATE DATE NOT NULL,
    START_TIME TIME NOT NULL,
    END_DATE DATE NOT NULL,
    END_TIME TIME NOT NULL,
    LOCATION VARCHAR(255),
    ORGANIZATION_ID VARCHAR(255),
    COURSE_ID VARCHAR(255),
    DEPARTMENT_ID VARCHAR(255),
    YEAR_LEVEL VARCHAR(20),
    STATUS VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Organization table
CREATE TABLE ORGANIZATION (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT_ID VARCHAR(255),
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Position table
CREATE TABLE POSITION (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ORGANIZATION_ID VARCHAR(255) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Student table
CREATE TABLE STUDENT (
    ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255) UNIQUE NOT NULL,
    STUDENT_ID VARCHAR(255) UNIQUE NOT NULL,
    YEAR_LEVEL VARCHAR(20) NOT NULL,
    DEPARTMENT_ID VARCHAR(255) NOT NULL,
    COURSE_ID VARCHAR(255) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Operator table
CREATE TABLE OPERATOR (
    ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255) UNIQUE NOT NULL,
    OPERATOR_ID VARCHAR(255) UNIQUE NOT NULL,
    ORGANIZATION_ID VARCHAR(255) NOT NULL,
    POSITION_ID VARCHAR(255) NOT NULL,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);

-- Attendance table
CREATE TABLE ATTENDANCE (
    ID VARCHAR(255) PRIMARY KEY,
    EVENT_ID VARCHAR(255) NOT NULL,
    STUDENT_ID VARCHAR(255) NOT NULL,
    CHECK_IN_TIME_AM TIME,
    CHECK_OUT_TIME_AM TIME,
    CHECK_IN_TIME_PM TIME,
    CHECK_OUT_TIME_PM TIME,
    DELETE_STATUS VARCHAR(8) DEFAULT 'ACTIVE'
);


INSERT INTO `users` (`ID`, `FIRST_NAME`, `LAST_NAME`, `PHONE_NUMBER`, `GENDER`, `ADDRESS`, `EMAIL`, `PASSWORD`, `ROLE`, `DELETE_STATUS`) VALUES ('123123', 'admin', 'admin', '09288383838', 'male', 'ADDSDASD', 'admin@gmail.com', 'password', 'admin', 'ACTIVE');